### ISSUE TITLE
[nitpicky] dictionary updates

### ISSUE THREAD

**Issue by faizandfurious** [ghmeier/one-log#2]
Your `OneLog.update` and `OneLog._format_kwargs` both mutate the original dictionary provided, //and// return the dictionary. This may cause unintended consequences if the consumer of this package either assumes the functions make a deepcopy and return a new, updated dictionary, or just uses a globally defined dictionary.

Either way, I recommend making the intentions of this behavior well documented. Either go 100% with mutating the original dictionary (and //don't// return the dictionary), or make a `copy.deepcopy` of the provided dictionary, mutate that instance, and return.

**Comment by ghmeier** [comment]
I definitely agree with you. When I initially made this, I wanted both properties so you could sort of functionally string the methods together on one line, and mutating it internally made it so you didn't have to redo calls. 

However not copying has too many unintended side effects. I'll be deep copying objects now.

**Comment by faizamodo** [comment]
Nice! Thanks for the quick turnaround
